[project]
name = "mongo-gen"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = []

[project.scripts]
mongo-gen = "mongo_gen.cli:main"

[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
